import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-text px-6 py-12">
      <div className="max-w-2xl mx-auto space-y-6">
        <Link href="/" className="text-xs text-blue font-semibold">← Home</Link>
        <h1 className="text-2xl font-black text-white">Terms of Service</h1>
        <p className="text-sm text-text-dark">Last updated: September 2026</p>
        <div className="space-y-4 text-sm text-text leading-relaxed">
          <section>
            <h2 className="text-base font-bold text-white mb-1">1. Eligibility</h2>
            <p>You must be 18 or older (or the legal age in your jurisdiction) and not resident in a jurisdiction where binary options trading is prohibited. Accounts failing verification are restricted.</p>
          </section>
          <section>
            <h2 className="text-base font-bold text-white mb-1">2. Trading risk</h2>
            <p>Binary options carry a high risk of loss. Prices on demo and OTC instruments are generated by the platform for trading purposes and may differ from live market prices. Never trade money you cannot afford to lose.</p>
          </section>
          <section>
            <h2 className="text-base font-bold text-white mb-1">3. Accounts and verification</h2>
            <p>Withdrawals require a verified email. Tier 1 identity verification raises limits and speeds review. False information leads to suspension.</p>
          </section>
          <section>
            <h2 className="text-base font-bold text-white mb-1">4. Deposits and withdrawals</h2>
            <p>Deposits are credited after manual verification. Withdrawals are subject to a 20% treasury reserve requirement and may be delayed during review. A 2% processing fee may apply (min $1, max $50).</p>
          </section>
          <section>
            <h2 className="text-base font-bold text-white mb-1">5. Fair use</h2>
            <p>Multiple accounts, bonus abuse, collusion, and exploitation of errors are prohibited and lead to forfeiture and bans.</p>
          </section>
          <section>
            <h2 className="text-base font-bold text-white mb-1">6. Responsible trading</h2>
            <p>Daily deposit limits and self-exclusion (24h to permanent) are available under More → Limits. These protections cannot be shortened once active.</p>
          </section>
          <section>
            <h2 className="text-base font-bold text-white mb-1">7. Liability</h2>
            <p>The platform is provided as-is. To the maximum extent permitted by law, liability is limited to account balances held at the time of an incident.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
