import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    DATABASE_URL: z.string().min(1),
    REDIS_URL: z.string().default("redis://localhost:6379"),
    BETTER_AUTH_SECRET: z.string().min(32),
    BETTER_AUTH_URL: z.string().url(),
    ADMIN_EMAIL: z.string().email().default("admin@nextorx.app"),
    ADMIN_PASSWORD: z.string().min(16, "Admin password must be at least 16 characters"),
    GOOGLE_CLIENT_ID: z.string().default(""),
    GOOGLE_CLIENT_SECRET: z.string().default(""),
    RESEND_API_KEY: z.string().default(""),
    RESEND_FROM_EMAIL: z.string().email().default("noreply@nextorx.app"),
    REDOTPAY_APP_KEY: z.string().default(""),
    REDOTPAY_PRIVATE_KEY: z.string().default(""),
    REDOTPAY_KEY_VERSION: z.string().default("1"),
    REDOTPAY_BASE_URL: z.string().url().default("https://acquirersandbox.rp-2023app.com"),
    REDOTPAY_MERCHANT_NAME: z.string().default("NextOrx"),
    NOWPAYMENTS_API_KEY: z.string().default(""),
    NOWPAYMENTS_IPN_SECRET: z.string().default(""),
    NOWPAYMENTS_BASE_URL: z.string().url().default("https://api-sandbox.nowpayments.io"),
  },
  client: {},
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    REDIS_URL: process.env.REDIS_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    REDOTPAY_APP_KEY: process.env.REDOTPAY_APP_KEY,
    REDOTPAY_PRIVATE_KEY: process.env.REDOTPAY_PRIVATE_KEY,
    REDOTPAY_KEY_VERSION: process.env.REDOTPAY_KEY_VERSION,
    REDOTPAY_BASE_URL: process.env.REDOTPAY_BASE_URL,
    REDOTPAY_MERCHANT_NAME: process.env.REDOTPAY_MERCHANT_NAME,
    NOWPAYMENTS_API_KEY: process.env.NOWPAYMENTS_API_KEY,
    NOWPAYMENTS_IPN_SECRET: process.env.NOWPAYMENTS_IPN_SECRET,
    NOWPAYMENTS_BASE_URL: process.env.NOWPAYMENTS_BASE_URL,
  },
  emptyStringAsUndefined: true,
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
