export interface MockTransaction {
  id: string;
  userId: string;
  userName: string;
  type: 'deposit' | 'withdrawal';
  method: 'card' | 'crypto' | 'bank_transfer' | 'e_wallet';
  amount: number;
  currency: string;
  status: 'pending' | 'approved' | 'rejected' | 'completed';
  reference: string;
  details: string;
  createdAt: string;
  processedAt: string | null;
  processedBy: string | null;
}

export const mockTransactions: MockTransaction[] = [
  {
    id: 'txn1',
    userId: '1',
    userName: 'John Doe',
    type: 'deposit',
    method: 'card',
    amount: 500,
    currency: 'USD',
    status: 'completed',
    reference: 'dep_abc123',
    details: 'Visa ****4532',
    createdAt: '2026-08-28T08:00:00Z',
    processedAt: '2026-08-28T08:05:00Z',
    processedBy: 'System',
  },
  {
    id: 'txn2',
    userId: '2',
    userName: 'Jane Smith',
    type: 'withdrawal',
    method: 'crypto',
    amount: 1200,
    currency: 'USDT',
    status: 'pending',
    reference: 'wit_def456',
    details: 'TRC20: TXyz...1234',
    createdAt: '2026-08-28T09:30:00Z',
    processedAt: null,
    processedBy: null,
  },
  {
    id: 'txn3',
    userId: '6',
    userName: 'Emma Davis',
    type: 'deposit',
    method: 'bank_transfer',
    amount: 3000,
    currency: 'USD',
    status: 'completed',
    reference: 'dep_ghi789',
    details: 'Wire transfer - Chase Bank',
    createdAt: '2026-08-27T14:00:00Z',
    processedAt: '2026-08-28T10:00:00Z',
    processedBy: 'Admin',
  },
  {
    id: 'txn4',
    userId: '8',
    userName: 'Lisa Martinez',
    type: 'withdrawal',
    method: 'card',
    amount: 800,
    currency: 'USD',
    status: 'approved',
    reference: 'wit_jkl012',
    details: 'Visa ****7891',
    createdAt: '2026-08-28T07:15:00Z',
    processedAt: '2026-08-28T11:30:00Z',
    processedBy: 'Admin',
  },
  {
    id: 'txn5',
    userId: '11',
    userName: 'Robert Taylor',
    type: 'deposit',
    method: 'crypto',
    amount: 5000,
    currency: 'BTC',
    status: 'completed',
    reference: 'dep_mno345',
    details: 'BTC: bc1q...abc',
    createdAt: '2026-08-26T16:45:00Z',
    processedAt: '2026-08-26T17:30:00Z',
    processedBy: 'System',
  },
  {
    id: 'txn6',
    userId: '14',
    userName: 'Patricia White',
    type: 'withdrawal',
    method: 'e_wallet',
    amount: 600,
    currency: 'USD',
    status: 'rejected',
    reference: 'wit_pqr678',
    details: 'Skrill: test@email.com',
    createdAt: '2026-08-27T12:00:00Z',
    processedAt: '2026-08-27T14:00:00Z',
    processedBy: 'Admin',
  },
  {
    id: 'txn7',
    userId: '16',
    userName: 'Nancy Clark',
    type: 'deposit',
    method: 'card',
    amount: 250,
    currency: 'USD',
    status: 'pending',
    reference: 'dep_stu901',
    details: 'Mastercard ****1234',
    createdAt: '2026-08-28T10:15:00Z',
    processedAt: null,
    processedBy: null,
  },
  {
    id: 'txn8',
    userId: '18',
    userName: 'Sandra Walker',
    type: 'withdrawal',
    method: 'crypto',
    amount: 1500,
    currency: 'ETH',
    status: 'pending',
    reference: 'wit_vwx234',
    details: 'ERC20: 0xAbC...5678',
    createdAt: '2026-08-28T11:00:00Z',
    processedAt: null,
    processedBy: null,
  },
  {
    id: 'txn9',
    userId: '10',
    userName: 'Jennifer Lee',
    type: 'deposit',
    method: 'bank_transfer',
    amount: 2000,
    currency: 'USD',
    status: 'approved',
    reference: 'dep_yza567',
    details: 'DBS Bank - Singapore',
    createdAt: '2026-08-25T09:00:00Z',
    processedAt: '2026-08-26T10:00:00Z',
    processedBy: 'Admin',
  },
  {
    id: 'txn10',
    userId: '20',
    userName: 'Karen Young',
    type: 'withdrawal',
    method: 'bank_transfer',
    amount: 4000,
    currency: 'USD',
    status: 'completed',
    reference: 'wit_bcd890',
    details: 'Emirates NBD - UAE',
    createdAt: '2026-08-24T15:30:00Z',
    processedAt: '2026-08-25T09:00:00Z',
    processedBy: 'System',
  },
];
