ALTER TABLE "User" ADD COLUMN "demoBalance" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LedgerEntry" ADD COLUMN "wallet" TEXT NOT NULL DEFAULT 'real';
ALTER TABLE "Trade" ADD COLUMN "wallet" TEXT NOT NULL DEFAULT 'real';
